config/routes.rb
Greenhousery::Application.routes.draw do
  resources :points
  resources :users
  resources :projects
  resources :project_arrays
  resources :sessions
  resources :solar_modules

  get "home/about"
  get "home/index"
  get "home/test"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "/project_array/:id/edit_modules" => "project_arrays#edit_modules", :as => "edit_modules"
  
  get "/project_array/:id/edit_layout" => "project_arrays#edit_layout", :as => "edit_layout"
  post "update_layout" => "project_arrays#update_layout", :as => "update_layout"

  post "update_measurements" => "project_arrays#update_measurements", :as => "update_measurements"
  post "update_module" => "project_arrays#update_module", :as => "update_module"

  post "format_point" => "points#format_point", :as => "format"

  root 'home#index'
  

end

app/models/project_array.rb
class ProjectArray < ActiveRecord::Base
  belongs_to :project
  belongs_to :solar_module
  attr_accessor :new_solar_module_brand, :new_solar_module_model, :new_solar_module_length, :new_solar_module_width, :new_solar_module_height, :new_solar_module_nominal_wattage
  has_many :points
  validates :project_id, presence: true
  after_validation :set_name
  before_save :update_square_foot

  def get_number_of_panels
    horizontal = self.solar_module.width + self.panel_spacing_side
    vertical = self.solar_module.length + self.panel_spacing_back
    array_width_feet = Unitwise(self.width, 'foot')
    array_width_inches = array_width_feet.convert('inch')
    number_panels_per_row = (array_width_inches / horizontal).value.to_i
    array_length_feet = Unitwise(self.length, 'foot')
    array_length_inches = array_length_feet.convert('inch')
    number_of_rows = (array_length_inches / vertical).value.to_i
    predicted_panels = number_panels_per_row * number_of_rows
  end

  def get_predicted_kw
    watts = get_number_of_panels * self.solar_module.nominal_wattage
    wattage_unit = Unitwise(watts, 'watt')
    wattage_unit.convert('kilowatt').value
  end

  def convert_meter_to_feet(unit)
    distance = Unitwise(unit.to_i, 'meter')
    distance.convert('foot').value
  end

  def update_square_foot
    unless self.width.blank?
      self.sqft = self.width * self.length
    end
  end

  def convert_sq_meter_to_sq_feet(unit)
    distance = Unitwise(unit.to_i, 'm2')
    distance.convert('foot2').value
  end

  def to_plugin
    fname = "module_plugin.rb"
    somefile = File.open(fname, "w")
    somefile.puts "require 'sketchup.rb'"
    somefile.puts "UI.menu('PlugIns').add_item('Generate " + self.solar_module.brand + " " + self.solar_module.model + "') { Panel.new }"
    somefile.puts "class Panel"
    somefile.puts "  attr_reader :run, :width, :thickness"
    somefile.puts "  def initialize"
    somefile.puts "    @run = " + self.solar_module.width.to_s
    somefile.puts "    @width = " + self.solar_module.length.to_s
    somefile.puts "    @thickness = " + self.solar_module.height.to_s
    somefile.puts "    draw_panel"
    somefile.puts "  end"
    somefile.puts "  def draw_panel \n    model = Sketchup.active_model\n    group = model.entities.add_group\n    entities = group.entities\n    new_panel = entities.add_face(coordinates[0], coordinates[1], coordinates[2], coordinates[3])\n    new_panel.reverse!\n    new_panel.pushpull(thickness, true)\n    group.to_component\n  end"
    somefile.puts "  def coordinates\n    x1 = 0\n    x2 = width\n    y1 = 0\n    y2 = run\n    pts = []\n    pts[0] = [x1, y1]\n    pts[1] = [x2, y1]\n    pts[2] = [x2, y2]\n    pts[3] = [x1, y2]\n    pts\n  end"
    somefile.puts "end"
    somefile.close
    file = File.open(fname, "r")
    file.read
  end

  def create_solar_module(params)
    solar_module = SolarModule.new
    solar_module.brand = params[:new_solar_module_brand]
    solar_module.model = params[:new_solar_module_model]
    solar_module.length = params[:new_solar_module_length].to_d
    solar_module.width = params[:new_solar_module_width].to_d
    solar_module.height = params[:new_solar_module_height].to_d
    solar_module.nominal_wattage = params[:new_solar_module_nominal_wattage].to_i
    if solar_module.save
      self.update_attributes(:solar_module_id => solar_module.id)
    end
  end

  def set_points(args)
    unless args[:length]
      args[:length] = args[:square_foot] / args[:width]
    end
    unless args[:width]
      args[:width] = args[:square_foot] /args[:length]
    end
    point1 = Point.new(x_coordinate: 0, y_coordinate: 0)
    point2 = Point.new(x_coordinate: args[:width], y_coordinate: 0)
    point3 = Point.new(x_coordinate: 0, y_coordinate: args[:length])
    point4 = Point.new(x_coordinate: args[:width], y_coordinate: args[:length])
    points = [point1, point2, point3, point4]
    points.each do |point|
      point.z_coordinate = 0
      point.project_array_id = self.id
      point.save
    end
  end

  def one_point(args)
    
  end
  

  def set_name
    unless self.name
      self.name = "#{self.project.name} Array"
      self.save
    end
  end
end

app/controllers/project_arrays_controller.rb
class ProjectArraysController < ApplicationController
  respond_to :html, :json  

  def index
    @project_array = ProjectArray.find(params[:id])
    respond_to do |format|
      format.rb { send_data @project_array.to_plugin }
    end
  end

  def new
    @project_array = ProjectArray.new
  end

  def create
    @project_array = ProjectArray.new(project_array_params)
    if @project_array.save
      redirect_to @project_array.project
    else
      render 'new'
    end
  end

  def show
    @project_array = ProjectArray.find(params[:id])
    redirect_to @project_array.project  
  end

  def update
    @project_array = ProjectArray.find(params[:id])
    @project_array.update_attributes(project_array_params)
    if @project_array.kw_goal.blank?
      redirect_to edit_layout_path(@project_array)
    else
      respond_with @project_array
    end
  end

  def update_layout
    new_params = params["post"]
    @project_array = ProjectArray.find(new_params[:id])
    @project_array.panel_spacing_side = new_params[:panel_spacing_side]
    @project_array.panel_spacing_back = new_params[:panel_spacing_back]
    @project_array.tilt_degrees = new_params[:tilt_degrees]
    @project_array.horizontal = new_params[:horizontal]
    @project_array.kw_goal = new_params[:kw_goal]
    @project_array.save
    @project_array.panel_count_predicted = @project_array.get_number_of_panels
    @project_array.kw_predicted = @project_array.get_predicted_kw
    @project_array.save
    redirect_to @project_array.project
  end

  def update_module
    new_params = module_update_params
    @project_array = ProjectArray.find(new_params[:id])
    @project_array.create_solar_module(module_update_params)
    redirect_to edit_layout_path(@project_array)
  end
 
  def update_measurements
    new_params = params["post"]
    @project_array = ProjectArray.find(new_params[:id])
    @project_array.length = @project_array.convert_meter_to_feet(new_params[:length])
    @project_array.width = @project_array.convert_meter_to_feet(new_params[:width])
    @project_array.save
    redirect_to edit_modules_path(@project_array)
  end
  
  def edit
    @project_array = ProjectArray.find(params[:id])
    gon.latitude = @project_array.project.latitude
    gon.longitude = @project_array.project.longitude
  end

  def edit_layout
    @project_array = ProjectArray.find(params[:id])
  end

  def edit_modules
    @project_array = ProjectArray.find(params[:id])
  end

  private
  
  def project_array_params
    params.require(:project_array).permit(:name, :project_id, :sqft, :solar_module_id, :length, :width, :panel_spacing_side, :panel_spacing_back, :tilt_degrees, :horizontal, :kw_predicted, :kw_goal, :panel_count_predicted, :new_solar_module_brand, :new_solar_module_model, :new_solar_module_length, :new_solar_module_height, :new_solar_module_width, :new_solar_module_nominal_wattage)
  end

  def module_update_params
    params.require(:post).permit(:id, :solar_module_id, :new_solar_module_brand, :new_solar_module_model, :new_solar_module_length, :new_solar_module_height, :new_solar_module_width, :new_solar_module_nominal_wattage)
  end

end

app/views/project_arrays/edit.html.erb
<div class="project-planning-block">
  <h1><%= best_in_place @project_array, :name %></h1>
  <h4><%= @project_array.project.address %></h4>
  Please fill out length and width and the array.
  Use the map below to get meter measurements.<br />
</div>
<hr>
<%= form_for @project_array, as: :post, url: update_measurements_path,
  method: :post do |f| %>
  <%= f.hidden_field :id, :value => @project_array.id %>
  <b><%= f.label "Length of Array:" %></b>
  <%= f.number_field :length, :step => 'any' %> meters<br />
  <em>Length is the vertical (north to south) measurement</em><br />
  <b><%= f.label "Width of Array:" %></b>
  <%= f.number_field :width, :step => 'any' %> meters<br />
  <em>Width is the horizontal (east to west) measurement</em><br />
  <%= f.submit %>
<% end %>
<hr>
<%= render "maps/map" %>

app/views/project_arrays/edit_layout.html.erb
<div class="project-planning-block">
  <h1><%= best_in_place @project_array, :name %></h1>
  <h4><%= @project_array.project.address %></h4>
  Please select a module or add your own module information<br />
</div>
<hr>
   <p>
        <%= form_for @project_array, as: :post, url:
        update_layout_path, method: :post do |f| %>
          <label for="project_array_solar_module_id">
            Solar Module
          </label><br />
          <%= f.hidden_field :id, :value => @project_array.id %>
          <%= f.label "Inches of Space Between Panels" %>
          <%= f.number_field :panel_spacing_side %> inch<br />
          <%= f.label "Spacing Between Rows" %>
          <%= f.number_field :panel_spacing_back %> inch<br />
          <%= f.label "Degree of tilt" %>
          <%= f.number_field :tilt_degrees %><br />
          <%= f.label "Horizontal Orientation?" %>
          <%= f.check_box :horizontal %><br />
          <%= f.label "Desired KW goal" %>
          <%= f.number_field :kw_goal %><br />
          <%= f.submit %>
<% end %>

app/views/project_arrays/edit_modules.html.erb
<div class="project-planning-block">
  <h1><%= best_in_place @project_array, :name %></h1>
  <h4><%= @project_array.project.address %></h4>
  Please select a module or add your own module information<br />
</div>
<hr>
   <p>
        <%= form_for @project_array do |f| %>
          <label for="project_array_solar_module_id">
            Select a Solar Module
          </label><br />
          <%= f.collection_select :solar_module_id,
          SolarModule.order(:brand), :id, :display, :prompt => "Select a Module"
          %>
          <%= f.submit "Select Module", :class => 'button' %>
        <% end %>
<hr>
        Or Create One!
        <%= form_for @project_array, as: :post, url:
      update_module_path, method: :post do |f| %>
          <%= f.hidden_field :id, :value => @project_array.id %>
          <%= f.label "Brand:" %>
          <%= f.text_field :new_solar_module_brand %>
          <%= f.label "Model:" %>
          <%= f.text_field :new_solar_module_model %><br />
          <%= f.label "Length:" %>
          <%= f.number_field :new_solar_module_length, :step => 'any'
        %> (inches) <br />
          <%= f.label "Width:" %>
          <%= f.number_field :new_solar_module_width, :step => 'any'
        %> (inches) <br />
          <%= f.label "Height:" %>
          <%= f.number_field :new_solar_module_height, :step => 'any'
        %> (inches) <br />
          <%= f.label "Nominal Wattage:" %>
          <%= f.number_field :new_solar_module_nominal_wattage %> <br />
          <%= f.submit "Create Custom Module Type", :class => 'button'%>
        <% end %>