config/routes.rb
Greenhousery::Application.routes.draw do
  resources :points
  resources :users
  resources :projects
  resources :project_arrays
  resources :sessions
  resources :solar_modules

  get "home/about"
  get "home/index"
  get "home/test"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "/project_array/:id/edit_modules" => "project_arrays#edit_modules", :as => "edit_modules"
  
  get "/project_array/:id/edit_layout" => "project_arrays#edit_layout", :as => "edit_layout"
  post "update_layout" => "project_arrays#update_layout", :as => "update_layout"

  post "update_measurements" => "project_arrays#update_measurements", :as => "update_measurements"
  post "update_module" => "project_arrays#update_module", :as => "update_module"

  post "format_point" => "points#format_point", :as => "format"

  root 'home#index'
  

end

app/models/user.rb
 class User < ActiveRecord::Base
  authenticates_with_sorcery!
  geocoded_by :address
  #after_validation :geocode
  has_many :projects
  validates :password, presence: true, confirmation: true, length: {minimum: 3}
  validates :email, presence: true, uniqueness: true
  validates :password_confirmation, presence: true


  def address
    [street, city, state, country].compact.join(', ')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to @user, :notice => "Signed up!"
    else
      #flash[:alert] = "Something went wrong!"
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    gon.latitude = @user.latitude
    gon.longitude = @user.longitude
  end

  private

  def user_params
    params.require(:user).permit(:email, :street, :city, :state, :country, :password, :password_confirmation)
  end

end

app/views/users/new.html.erb
<div id="user-data">
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_message">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :email %>
    <%= f.text_field :email %><br />
    <%= f.label :password %>
    <%= f.password_field :password %> <br />
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %> <br />
    <%= f.submit :value => "Sign Up" %>
  <% end %>
</div>

app/views/users/show.html.erb
<% if current_user.projects.any? %>
  <div id="projects">
    <h3>Your Projects</h3>
    <ul>
      <% current_user.projects.each do |project| %>
        <li><%= link_to "#{project.name}", project_path(project) %> 
          <%= project.address %></li>
      <% end %>
    <ul>
  </div>
<% end %>  

<div id="new-project">
  <%= button_to('Start a New Project', new_project_path, :method =>
  :get, :class => "button") %>
</div>