config/routes.rb
Greenhousery::Application.routes.draw do
  resources :points
  resources :users
  resources :projects
  resources :project_arrays
  resources :sessions
  resources :solar_modules

  get "home/about"
  get "home/index"
  get "home/test"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "/project_array/:id/edit_modules" => "project_arrays#edit_modules", :as => "edit_modules"
  
  get "/project_array/:id/edit_layout" => "project_arrays#edit_layout", :as => "edit_layout"
  post "update_layout" => "project_arrays#update_layout", :as => "update_layout"

  post "update_measurements" => "project_arrays#update_measurements", :as => "update_measurements"
  post "update_module" => "project_arrays#update_module", :as => "update_module"

  post "format_point" => "points#format_point", :as => "format"

  root 'home#index'
  

end

app/views/shared/_flash_message.html.erb
<% [:notice, :error, :alert, :success].each do |level| %>
  <% unless flash[level].blank? %>
    <div class="flash-message <%= flash_class(level) %>" >
      <a class="close" href="#">×</a><%= content_tag :p, flash[level] %>
    </div>
    <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <h1><%= link_to "GreenHousery", '/', id: "logo" %></h1>
      <nav>
        <ul class="nav pull-right">
          <% if current_user %>
            <li><%= link_to 'Dashboard', user_path(current_user) %></li>
            <li><%= link_to 'Logout', logout_path %></li>
          <% else %>
            <li> <%= link_to 'Sign Up', new_user_path %></li>
            <li> <%= link_to 'Login', login_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>