config/routes.rb
Greenhousery::Application.routes.draw do
  resources :points
  resources :users
  resources :projects
  resources :project_arrays
  resources :sessions
  resources :solar_modules

  get "home/about"
  get "home/index"
  get "home/test"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "/project_array/:id/edit_modules" => "project_arrays#edit_modules", :as => "edit_modules"
  
  get "/project_array/:id/edit_layout" => "project_arrays#edit_layout", :as => "edit_layout"
  post "update_layout" => "project_arrays#update_layout", :as => "update_layout"

  post "update_measurements" => "project_arrays#update_measurements", :as => "update_measurements"
  post "update_module" => "project_arrays#update_module", :as => "update_module"

  post "format_point" => "points#format_point", :as => "format"

  root 'home#index'
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  geocoded_by :address
  after_validation :geocode
  belongs_to :user
  has_many :project_arrays

  def address
    [street, city, state, country].compact.join(', ')
  end

  def get_station_data
    nrel = NrelCall.new({:lat => self.latitude, :lon => self.longitude})
    data = nrel.get_data
    #if !data[:error]
      formatted_data = format_station_data(data)
      self.update_attributes(formatted_data)
    #end
  end

  def format_station_data(data)
    formatted_data = {}
    formatted_data[:station_city] = data["city"]
    formatted_data[:station_state] = data["state"]
    formatted_data[:distance_from_station] = data["distance"]
    formatted_data[:station_elevation] = data["elevation"]
    formatted_data[:station_timezone] = data["timezone"]
    formatted_data
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html, :json  

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.state = params[:state]
    @project.user_id = current_user.id if current_user
    if @project.save
      @project_array = ProjectArray.create(project: @project)
      @project.get_station_data
      redirect_to edit_project_array_path(@project_array)
    else
      render 'new'
    end
  end

  def show
    @project = Project.find(params[:id])
    @project_arrays = @project.project_arrays
    gon.latitude = @project.latitude
    gon.longitude = @project.longitude
  end

  def update
    @project = Project.find(params[:id])
    @project.update_attributes(project_params)
    respond_with @project
  end
 
  def edit
  end

  private
  
  def project_params
    params.require(:project).permit(:name, :user_id, :street, :city, :state, :country, :latitude, :longitude, :sqft)
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project_array.html.erb
<% @project_arrays.each do |project_array| %>
    <h2><%= best_in_place project_array, :name %></h2>
    Square Footage: <%= project_array.sqft.ceil %> square feet<br />
    
    Width: <%= best_in_place project_array, :width %> feet<br />
    Length: <%= best_in_place project_array, :length %> feet<br />
    <p>
      <% if project_array.solar_module %>
        <b>Module Type:</b> <%= project_array.solar_module.display
        %><br />
        Download:
        <%= link_to "Ruby Plugin", project_arrays_path(id: project_array, format:
          "rb") %>
      <% else %>
        <%= form_for project_array do |f| %>
          <label for="project_array_solar_module_id">
            Solar Module
          </label><br />
          <%= f.collection_select :solar_module_id,
          SolarModule.order(:brand), :id, :display, :prompt => "Select a Module"
          %>
          <%= f.submit %>
        <% end %>
        Or Create One!
        <%= form_for project_array, as: :post, url:
      update_module_path, method: :post do |f| %>
          or create one:
          <%= f.hidden_field :id, :value => project_array.id %>
          <%= f.text_field :new_solar_module_brand %>
          <%= f.text_field :new_solar_module_model %>
          <%= f.number_field :new_solar_module_length, :step => 'any' %>
          <%= f.number_field :new_solar_module_width, :step => 'any' %>
          <%= f.number_field :new_solar_module_height, :step => 'any' %>
          <%= f.number_field :new_solar_module_nominal_wattage %>
          <%= f.submit %>
        <% end %>
      <% end %>
    <br />
    <p>
    <h3>KW Goal: <%= project_array.kw_goal %>kw</h3>
   <b> Max Predicted KW:</b> <%= project_array.kw_predicted %><br />
   <b> Max Panel Count:</b> <%= project_array.panel_count_predicted %><br />
   <b> Tilt Degree:</b>  <%= project_array.tilt_degrees %> degrees<br />
   <b> Spacing between panels:</b>  <%= project_array.panel_spacing_side %> inch(es)<br />
   <b> Spacing between rows:</b>  <%= project_array.panel_spacing_back %> inch(es)<br />
   <b> Horizontal Orientation:</b>  <%= project_array.horizontal %><br />
    </p>
  <% end %>

app/views/projects/new.html.erb
<div id="project-data">
  <%= form_for @project do |u| %>
    Project Name: <%= u.text_field :name %><br />
    Street Address: <%= u.text_field :street %><br />
    City: <%= u.text_field :city %><br />
    State: <%= select_tag :state, options_for_select(us_states) %><br />
    Country: <%= u.text_field :country %> <br />
    <%= u.submit :value => "Start Planning" %>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="project-planning-block">
  <h1> <%= best_in_place @project, :name %> </h1>
  <h2><b>Current Time on Site:</b>
    <em><%= Time.now.in_time_zone(@project.station_timezone).strftime("%B %d at %I:%M %p") %></em></h2>
   <b>Address:</b>
   <%= best_in_place @project, :street %> |
   <%= best_in_place @project, :city %> |
   <%= best_in_place @project, :state %> |
   <%= best_in_place @project, :country %> <br />
    <b>Latitude:</b> 
    <%= @project.latitude %>
    <b>Longitude:</b>
    <%= @project.longitude %><br />
</div>

<div id='project-array-data'>
  <%= render 'project_array' %>
</div>
<hr>
<div>
    <h2><b>Nearest Weather Station</b></h2>
    <b><%= @project.station_city %>, <%= @project.station_state %></b><br />
    <b>Distance from project:</b> <%= @project.distance_from_station %> meters<br />
    <b>Station Elevation:</b> <%= @project.station_elevation %> meters<br />
  <b>Station Timezone:</b> (relative to GMT): <%= @project.station_timezone %>
 </div>
<hr>

 <%= render "maps/map" %>